
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  template: template0

development:
  <<: *default
  database: onlymembers_development

test:
  <<: *default
  database: onlymembers_test

production:
  <<: *default
  database: onlymembers_production
